"""empty message

Revision ID: be721d1c560d
Revises: e830aa22218a
Create Date: 2025-05-05 18:35:48.963768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be721d1c560d'
down_revision = 'e830aa22218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen_cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=50), nullable=True))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen_cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
